Movie_Gallery/movie_project/movie_app/urls.py
from django.urls import path
from . import views
from .views import movie_list_by_genre

app_name='movie_app'

urlpatterns=[
    path('',views.home,name='home'),
    path('detail/<int:movie_id>',views.movie_detail,name='movie_detail'),
    path('add/',views.movie_add,name='movie_add'),
    path('update/<int:id>',views.movie_update,name='movie_update'),
    path('delete/<int:id>',views.movie_delete,name='movie_delete'),
    path('genre/<int:genre_id>/', views.movie_list_by_genre, name='movie_list_by_genre'),
]

Movie_Gallery/movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls')),
    path('search/',include('search_app.urls')),
    path('user/',include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Movie_Gallery/movie_project/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'
urlpatterns=[

    path('',views.searchresult,name='SearchResult'),

]

Movie_Gallery/movie_project/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('edit_user/',views.edit_user,name='edit_user'),
    path('profile/', views.view_profile, name='view_profile'),

]

Movie_Gallery/movie_project/movie_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.
from django.urls import reverse


class Genre(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title=models.CharField(max_length=250)
    poster=models.ImageField(upload_to='gallery')
    description=models.TextField()
    release_date=models.DateField()
    actors=models.TextField()
    genre=models.ForeignKey(Genre,on_delete=models.CASCADE,related_name='movies')
    youtube_link=models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)



    def __str__(self):
        return self.title

Movie_Gallery/movie_project/search_app/models.py
from django.db import models

# Create your models here.

Movie_Gallery/movie_project/user/models.py
from django.db import models

# Create your models here.

Movie_Gallery/movie_project/movie_app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['title','poster','description','release_date','actors','genre','youtube_link']

Movie_Gallery/movie_project/user/forms.py
from django import forms
from django.contrib.auth.models import User

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

Movie_Gallery/movie_project/movie_app/views.py
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator,InvalidPage,EmptyPage
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Movie,Genre
from .forms import MovieForm


# Create your views here.
def home(request):
    movie=Movie.objects.all()
    paginator = Paginator(movie, 6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        movies = paginator.page(page)
    except (EmptyPage, InvalidPage):
        movies = paginator.page(paginator.num_pages)
    return render(request,'home.html',{'movie':movie,'movies':movies})

def movie_detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'movie_detail.html',{'movie':movie})

def movie_add(request):
    if request.method == 'POST':
        form = MovieForm(request.POST,request.FILES)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('/')
    else:
        form = MovieForm()
    return render(request, 'movie_add.html', {'form': form})

def movie_update(request, id):
    movie = get_object_or_404(Movie, id=id)
    form = MovieForm(request.POST,request.FILES)
    if movie.user != request.user:
        raise PermissionDenied
    return render(request, 'movie_update.html', {'form':form})

def movie_delete(request, id):
    movie = get_object_or_404(Movie, id=id)
    if movie.user != request.user:
        raise PermissionDenied
    movie.delete()
    return redirect('/')





def movie_list_by_genre(request, genre_id):
    genre = Genre.objects.get(pk=genre_id)
    movies = Movie.objects.filter(genre=genre)
    return render(request, 'movies_by_genre.html', {'genre': genre, 'movies': movies})

Movie_Gallery/movie_project/search_app/views.py
from django.shortcuts import render
from movie_app.models import Movie
from django.db.models import Q

# Create your views here.
def searchresult(request):
    movies=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        movies=Movie.objects.all().filter( Q(title__contains=query) | Q(description__contains=query))
    return render(request,'movie_search.html',{'query':query,'movies':movies})

Movie_Gallery/movie_project/user/views.py
from django.shortcuts import render,redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import UserEditForm

# Create your views here.
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        firstname = request.POST['first_name']
        lastname = request.POST['last_name']
        emailid = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username already exists')
                return redirect('register')
            elif User.objects.filter(email=emailid).exists():
                messages.info(request,'email address already exists')
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,first_name=firstname,last_name=lastname,email=emailid,password=password)
                user.save()
                print('user created')
        else:
            messages.info(request,'password not matching')
            return redirect('register')
        return redirect('login')

    return render(request,'register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid credentials')
            return redirect('login')
    return render(request,'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def view_profile(request):
    return render(request, 'view_profile.html', {'user': request.user})

def edit_user(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('view_profile')
    else:
        form = UserEditForm(instance=request.user)
    return render(request, 'edit_user.html', {'form': form})

Movie_Gallery/movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <script src="https://kit.fontawesome.com/928bab6617.js" crossorigin="anonymous"></script>

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

Movie_Gallery/movie_project/templates/edit_user.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit Your Information</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
</form>
{% endblock %}

Movie_Gallery/movie_project/templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">&copy; MG Private Limited. All rights reserved</p>
</div>

Movie_Gallery/movie_project/templates/header.html
{% load static %}
<header>
    <center>
        <a href=""></a><img src="{% static 'image/logo.png' %}" alt="logimage" width="130px;" height="130px; ">
    </center>
</header>

Movie_Gallery/movie_project/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img class="my_image my_image_padding" src="{% static 'image/Banner.png' %}" alt="our movies" width="1250px;">
</div>
<br>
<div>
    <h1 class="text-center my_title">Our Movie Collections</h1>
    <p class="text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.</p>
</div><br>
<div claas="container">
    <div class="row mx_auto">
        {% for i in movies.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="height:350px;width:290px;">
                <a href="{% url 'movie_app:movie_detail' i.id %}"><img class="card-img-top my_image" src="{{i.poster.url}}" alt="{{i.name}}" style="height:250px;width:250px;"></a>
                <div class="card-body">
                    <h4>{{i.title}}</h4>
                    <p>{{i.description}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div><br>
    <div class="mx_auto">
        {% if movies.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in movies.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if movies.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div><br>



{% endblock %}

Movie_Gallery/movie_project/templates/login.html
{% extends 'base.html' %}
{% block content %}
<center>
  <form action="login" method="post">
      {% csrf_token %}
     <br> Username<input type="text" name="username" placeholder="enter your username"><br>
     <br>  Password<input type="password" name="password" placeholder="enter your password"><br>
                 <br>  <input type="submit">

  </form>
</center>
{% block css %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .footer {
        margin-top: auto;
    }
</style>
{% endblock %}


<div class="footer">
    <!-- Your footer content goes here -->
</div>
{% endblock %}

Movie_Gallery/movie_project/templates/movie_delete.html
<form method="post">
    {% csrf_token %}
    <p>are u sure you want to delete this movie?</p>
    <input type="submit">
</form>

Movie_Gallery/movie_project/templates/movie_detail.html
{% extends 'base.html' %}
{% block content %}

<br><center>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.poster.url}}" width="300" height="300"><br>
        </div>
        <div class="col-md-6">
            <h3>{{movie.title}}</h3>
            <h3>{{movie.description}}</h3>
            <h3>{{movie.release_date}}</h3>
            <h3>{{movie.actors}}</h3>
            <a href="{{movie.youtube_link}}" target="_blank">{{movie.youtube_link}}</a><br><br>
            {% if movie.user == request.user %}
            <a class="btn btn-warning" href="{% url 'movie_app:movie_update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movie_app:movie_delete' movie.id %}" onclick="return confirm('Are you sure?');">delete</a>
            {% endif %}
        </div>
    </div>
</div>
    </center><br>
{% block css %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .footer {
        margin-top: auto;
    }
</style>
{% endblock %}


<div class="footer">
    <!-- Your footer content goes here -->
</div>

{% endblock %}

Movie_Gallery/movie_project/templates/movie_search.html
{% extends 'base.html' %}
{% block content %}
<div>
    <p class="text-center my_search_text">you have searched for: <b>"{{query}}"</b></p>
</div>

<div class="container">
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="height:350px;width:290px;">
                <a href=""><img class="card-img-top my_image" src="{{movie.poster.url}}" alt="{{movie.title}}" style="height:250px;width:250px;"></a>
                <div class="card-body">
                    <h4>{{movie.title}}</h4>
                    <p>{{movie.description}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div>
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>


    </div>
</div>

{% block css %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .footer {
        margin-top: auto;
    }
</style>
{% endblock %}


<div class="footer">
    <!-- Your footer content goes here -->
</div>

{% endblock %}

Movie_Gallery/movie_project/templates/movie_update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
  <div class="card-header">
    <div class="card-title">
      <h3>Movie update</h3>
      <div class="card-body">
          <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit">submit</button>
          </form>
      </div>
    </div>
  </div>
</div>
{% block css %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .footer {
        margin-top: auto;
    }
</style>
{% endblock %}


<div class="footer">
    <!-- Your footer content goes here -->
</div>
{% endblock %}

Movie_Gallery/movie_project/templates/movies_by_genre.html
{% extends 'base.html' %}
{% block content %}


<center>
    <h1>{{ genre.name }}</h1>
<div claas="container">
    <div class="row mx_auto">
        {% for movie in movies %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="height:350px;width:290px;">
                <a href="{% url 'movie_app:movie_detail' movie.id %}"><img class="card-img-top my_image" src="{{movie.poster.url}}" alt="{{movie.name}}" style="height:250px;width:250px;"></a>
                <div class="card-body">
                    <h4>{{movie.title}}</h4>
                    <p>{{movie.description}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div><br>
</div>
</center>

{% block css %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .footer {
        margin-top: auto;
    }
</style>
{% endblock %}


<div class="footer">
    <!-- Your footer content goes here -->
</div>
{% endblock %}

Movie_Gallery/movie_project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'view_profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movie_app:movie_add' %}">Add Movie</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">logout</a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Explore
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            <li><a class="dropdown-item" href="/">All movies</a></li>
            {% for movie in movies %}
            <li><a class="dropdown-item" href="{% url 'movie_app:movie_list_by_genre' movie.genre.id %}">{{movie.genre.name}}</a></li>
            {% endfor %}



          </ul>
        </li>

<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

Movie_Gallery/movie_project/templates/register.html
{% extends 'base.html' %}
{% block content %}
<center>
    <form action="register" method="post">
        {% csrf_token %}
       <br> Username<input type="text" name="username" placeholder="enter your username"><br>
       <br> first_name<input type="text" name="first_name" placeholder="enter your firstname"><br>
       <br> last_name<input type="text" name="last_name" placeholder="enter your lastname"><br>
       <br> email<input type="email" name="email" placeholder="enter your email address"><br>
       <br> password<input type="password" name="password" placeholder="enter your password"><br>
       <br> confirm password<input type="password" name="password1" placeholder="confirm your password"><br>
        <br> <input type="submit">

    </form>
</center>
{% block css %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .footer {
        margin-top: auto;
    }
</style>
{% endblock %}


<div class="footer">
    <!-- Your footer content goes here -->
</div>
{% endblock %}

Movie_Gallery/movie_project/templates/view_profile.html
{% extends 'base.html' %}

{% block content %}
<h2>Profile Information</h2>
<div>
    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>First name:</strong> {{ user.first_name }}</p>
    <p><strong>Last name:</strong> {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p><br>
    <a href="{% url 'edit_user' %}">Edit Profile</a>

</div>
{% block css %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
    }

    .footer {
        margin-top: auto;
    }
</style>
{% endblock %}


<div class="footer">
    <!-- Your footer content goes here -->
</div>
{% endblock %}